<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<wsdl:definitions name="FileToRecetas" targetNamespace="http://xmlns.oracle.com/EjercicioIntegradorRecetas/ProyectoFinalIntegrador/FileToRecetas" xmlns:tns="http://xmlns.oracle.com/EjercicioIntegradorRecetas/ProyectoFinalIntegrador/FileToRecetas" xmlns:inp1="http://www.RecetasSchema.org" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.RecetasSchema.org" schemaLocation="../Schemas/RecetasSchema.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="Entrada" element="inp1:Entrada"/>
    </wsdl:message>
    <wsdl:portType name="Insert_ptt">
        <wsdl:operation name="Insert">
            <wsdl:input message="tns:requestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="Insert_bind" type="tns:Insert_ptt">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="Insert">
            <soap:operation style="document" soapAction="Insert"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://xmlns.oracle.com/EjercicioIntegradorRecetas/ProyectoFinalIntegrador/FileToRecetas"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>]]></con:wsdl>
    <con:dependencies>
        <con:schemaRef isInclude="false" schemaLocation="../Schemas/RecetasSchema.xsd" namespace="http://www.RecetasSchema.org" ref="ProyectoFinalIntegrador/Resources/Schemas/RecetasSchema"/>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/EjercicioIntegradorRecetas/ProyectoFinalIntegrador/FileToRecetas</con:targetNamespace>
</con:wsdlEntry>